Sprint 15
MaximAgarev/Tracker pull request #2
Opened 2023-05-09 13:10 UTC by MaximAgarev

В чек-листе указан NSFetchedResultsController, но теория изложена очень скомканно, как его применять и зачем ломать всю архитектуру приложения, совершенно непонятно. У меня все было заточено под протокол Storage, и правильным решением кажется именно замена storage под протокол, не трогая код остальных частей. Надеюсь, использование NSFetchedResultsController не критично.

2023-05-10 20:10 UTC, IBDesignable requested changes
К сожалению в ПР не вошли изменения по верстке – прокоментировать подробно не смогу, но если коротко то все-таки лучше работать с отдельными вьюшками-ячейками, и как можно меньше пользоваться свойсвтом tag - у вью. Любая коллекция / секция очень хорошо прототипируется enum-и, например секции таблицы можно было бы разбить на trackerName, trackerSettings, emoji, color 

С кор датой – у тебя хорошо получилось настроить взаимосвязи модели, но построить стек работы с базой данных не удалось до конца. Нужно докопать эту тему, привлечь Наставников на помощь)

2023-05-10 20:10 UTC, IBDesignable commented on Tracker/Application/AppDelegate.swift
> +        print("Documents Directory: ", FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).last ?? "Not Found!")
👀 уберем?

2023-05-10 20:10 UTC, IBDesignable commented on Tracker/Storage/StorageCoreData.swift
> +    let context = (UIApplication.shared.delegate as! AppDelegate).persistentContainer.viewContext
Я сожалею, что мои коллеги не упомянули что это упрощение не стоит копировать себе в проект. 

Конечно же никаких форс операций создавать нельзя, как и раньше. Да и создавать такие сущности прямо в AppDelegate – не очень красивая тактика.

Минимальными телодвижениями это можно поправить, сделав lazy свойство для контейнера прямо в этом сторадже TrackerStorageCoreData.

```swift
 private lazy var persistentContainer: NSPersistentContainer = {
        let container = NSPersistentContainer(name: "Tracker")
        container.loadPersistentStores { description, error in
            if let error = error {
                fatalError("Unable to load persistent stores: \(error)")
            }
        }
        return container
    }()
``` 

Креплю короткую памятку [по настройке контейнера](https://www.hackingwithswift.com/read/38/3/adding-core-data-to-our-project-nspersistentcontainer)

Так как сам сторадж доставляется как синглтон, для нас тогда не будет проблемы с гарантией что сторадж живет ровно один на сессию приложения.

тогда контекст для чтения можно будет организовать вычислимым свойством:

```swift
var readContext: NSManagedObjectContext {
  persistentContainer.viewContext
}
```

2023-05-10 20:10 UTC, IBDesignable commented on Tracker/Models/Tracker.xcdatamodeld/Tracker.xcdatamodel/contents
> +    </entity>
У любой записи в таблицы хорошо бы заранее определиться с уникальным ключом. В случае трекера у тебя есть trackerID, для категории можно тоже ввести id, но также можно ограничиться уникальностью названия. Для записей поле trackerID можно спутать со ссылкой на trackerID, поэтому лучше переназвать как recordID

2023-05-10 20:10 UTC, IBDesignable commented on Tracker/Storage/StorageCoreData.swift
> +        let searchTracker = try! context.fetch(trackerRequest)
try? / do-catch, guard/if – рекомендую не отступать от практики неиспользования форс операций

2023-05-10 20:10 UTC, IBDesignable commented on Tracker/Storage/StorageCoreData.swift
> +            let updatedTracker = searchTracker.first(where: { $0.category?.title == category?.title })
будет чуть попороще выглядеть код, если изначально разыменовать опциональное значение
```suggestion
        } else if let updatedTracker = searchTracker.first(where: { $0.category?.title == category?.title })
```

2023-05-10 20:10 UTC, IBDesignable commented on Tracker/Storage/StorageCoreData.swift
> +        trackerRequest.predicate = NSPredicate(format: "category.title == %@", category.title!)
почему бы не написать guard let title = category.title ?

2023-05-10 20:15 UTC, IBDesignable commented
Еще обратила внимание на верстку ячейки цвета, на мой взгляд дизайнер не очень удобно подготовил макет, чтобы сверстать и попасть в скругления. 

радусы должны отличаться на размер отступа по границе, вот [иллюстративный тред на тему в твиттере](https://twitter.com/gavmn/status/1545387084017532929)

И под конец еще заметила, что нужно цвет рамки подбирать под выбранный цвет – в работе остается серый, это надо поправить тоже (в фидбеке на платформе не выписала отдельно)

2023-05-13 14:52 UTC, MaximAgarev commented on Tracker/Models/Tracker.xcdatamodeld/Tracker.xcdatamodel/contents
> +    </entity>
А это и есть именно trackerID, т.е. трекера, для которого сохранена запись об отметке

2023-05-25 17:52 UTC, IBDesignable approved these changes
Давай поправим небольшие ошибки:
1) сильную ссылку на делегатов поправим на слабую
2) уберем странный delegate: AnyObject – либо добаим пояснение, зачем он такой красивый нужен.

2023-05-25 17:52 UTC, IBDesignable commented on Tracker/Controllers/CategoriesViewController.swift
>      var delegate: NewTrackerViewController?
ссылка на делегат сильная, будет утечка памяти. 
Давай проверим всю работу на предмет подобных ошибок

2023-05-25 17:52 UTC, IBDesignable commented on Tracker/Domain/DataProvider.swift
> +}
По количеству методов можно заподозрить наружение принципа SOLID I - разделение ответсвенности. 
Скорее всего здесь избыточно собрано все подряд, и нужно было декомпозировать на маленькие сервисы, чтобы было удобнее работать. Сервис который решает один вид задач для одного типа данных, например.

2023-05-25 17:52 UTC, IBDesignable commented on Tracker/Domain/DataProvider.swift
> +    var delegate: AnyObject? { get set }
var delegate: AnyObject? { get set } – это что-то странное :) 

вообще любой класс может быть делегатом? а зачем так широко? Кажется, тут тоже есть проблема в понимании.

Делегаты на то и закрывают протоколами, чтобы явно обозначить какие задачи делегат будет решать. Здесь явно была попытка обхитрить систему и срезать путь) так не пойдет.

Кажется, если его сейчас убрать – то вообще ничего не сломается)

2023-05-25 17:52 UTC, IBDesignable commented on Tracker/Application/AppDelegate.swift
> +import CoreData
можно уже удалить

2023-05-25 17:53 UTC, IBDesignable commented on Tracker/Models/Tracker.xcdatamodeld/Tracker.xcdatamodel/contents
> +    </entity>
окей, хорошо. пусть так.

2023-05-25 17:53 UTC, IBDesignable commented on Tracker/Domain/DataProvider.swift
> +}
Возможно это не так, но я бы задумалась :)

2023-05-25 18:48 UTC, ABashkirova commented on Tracker/Domain/DataProvider.swift
> +    }()
что тут хорошо: NSFetchedResultsController не торчит наружу в контроллере. А живет себе спокойно внутри дата-провайдера. 

Хорошо что настройка вся спрятана в замыкание.

Не очень хорошо вызвать fetch внутри настройки этого свойства. лучше отделать действия по настройке и действия активные, которые приведут к изменению состояния приложения.

2023-05-27 11:18 UTC, merged